name: Djj_zhongdou

on:
  schedule:
    - cron: '1 22,23,0-15/1 * * * '
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./djj/requirements.txt 
        
      - name: 'run 公众号iosrule' 
        run: python3 ./djj/zhongdou.py 
        env:
            JD_API_HOST: ${{ secrets.JD_API_HOST }}
            DJJ_BARK_COOKIE: ${{ secrets.DJJ_BARK_COOKIE }}
            DJJ_DJJ_COOKIE: ${{ secrets.DJJ_DJJ_COOKIE }}
            DJJ_SEVER_JIANG: ${{ secrets.DJJ_SEVER_JIANG }}
            
            
